### ISSUE TITLE
关于文章"Locks实现:背后不为人知的故事"中的一个描述

### ISSUE THREAD

**Issue by questocat** [hitzhangjie/myspace#159]
## 问题描述

博主你好！很抱歉，因为没有在你博客找到可以留言的地方，不知道是否可以在这里提问。

文章中[协程调度优化](https://www.hitzhangjie.pro/blog/2021-04-17-locks%E5%AE%9E%E7%8E%B0%E9%82%A3%E4%BA%9B%E4%B8%8D%E4%B8%BA%E4%BA%BA%E7%9F%A5%E7%9A%84%E6%95%85%E4%BA%8B/#%E5%8D%8F%E7%A8%8B%E8%B0%83%E5%BA%A6%E4%BC%98%E5%8C%96)部分有这样一段描述：“但是也只是将其标记为runnable之后丢到global queue而已”，我阅读了相关的代码似乎没有这种体现，都是标记为 _Grunnable 后放到 P 的 runnext，区别在于饥饿模式下执行了 `goyield`。

**Comment by hitzhangjie** [comment]
感谢反馈，很长一段时间没更新，
是的，都是goready runqput尝试先放到本地队列，不行的话才会尝试global queue，……，已纠正
